# Generated by Django 2.0.2 on 2018-03-05 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('unevu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='unevu.University')),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='university',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.CharField(default=' ', max_length=1000),
        ),
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='convener',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='course_convener', to='unevu.Teacher'),
        ),
        migrations.AddField(
            model_name='course',
            name='school',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='unevu.School'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='school',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='unevu.School'),
        ),
    ]
