# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unevu', '0004_auto_20180318_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
