# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-18 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unevu', '0005_university_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='university',
            name='lat',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='university',
            name='lng',
            field=models.FloatField(default=0.0),
        ),
    ]
