# Generated by Django 2.0.2 on 2018-03-20 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unevu', '0006_auto_20180318_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='avgRating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='noOfRatings',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='avgRating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='noOfRatings',
            field=models.FloatField(default=0),
        ),
    ]
