# Generated by Django 2.0.2 on 2018-03-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unevu', '0006_auto_20180318_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='avgReview',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='noOfReviews',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='avgReview',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='university',
            name='noOfReviews',
            field=models.IntegerField(default=0),
        ),
    ]
