# Generated by Django 2.0.2 on 2018-03-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unevu', '0007_auto_20180320_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='avgReview',
            new_name='avgRating',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='noOfReviews',
            new_name='noOfRatings',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='avgReview',
            new_name='avgRating',
        ),
        migrations.RenameField(
            model_name='university',
            old_name='noOfReviews',
            new_name='noOfRatings',
        ),
    ]
