# Generated by Django 2.0.2 on 2018-03-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unevu', '0008_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
