# Generated by Django 2.0.2 on 2018-03-21 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unevu', '0009_review_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='liked',
        ),
    ]
