# Generated by Django 2.0.2 on 2018-03-21 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unevu', '0009_auto_20180320_1201'),
        ('unevu', '0010_remove_review_liked'),
    ]

    operations = [
    ]
