# Generated by Django 2.0.2 on 2018-03-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unevu', '0009_auto_20180320_1201'),
        ('unevu', '0011_auto_20180321_1217'),
    ]

    operations = [
    ]
