# Generated by Django 2.0.2 on 2018-03-21 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unevu', '0012_merge_20180321_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='avgRating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='noOfRatings',
            field=models.FloatField(default=0),
        ),
    ]
