# Generated by Django 2.0.2 on 2018-03-22 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unevu', '0013_auto_20180321_2120'),
        ('unevu', '0011_merge_20180321_1230'),
    ]

    operations = [
    ]
