# Generated by Django 2.0.2 on 2018-03-22 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unevu', '0014_merge_20180322_0715'),
        ('unevu', '0016_request'),
    ]

    operations = [
    ]
