# Generated by Django 2.0.2 on 2018-03-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unevu', '0017_merge_20180322_2323'),
        ('unevu', '0010_auto_20180321_0804'),
    ]

    operations = [
    ]
